apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cvat-ui-gateway
  namespace: platform-evml
spec:
  servers:
    - port:
        number: 80
        name: http-ui
        protocol: HTTP
      hosts:
        - cvat-ui.cmh.platform-test2.evinternal.net
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cvat-ui-virtual-service
  namespace: platform-evml
spec:
  gateways:
    - cvat-ui-gateway
  hosts:
    - cvat-ui.cmh.platform-test2.evinternal.net
  http:
    - route:
        - destination:
            host: cvat-ui
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvat-ui
  namespace: platform-evml
  labels:
    app: cvat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvat-ui
  template:
    metadata:
      labels:
        app: cvat-ui
    spec:
      containers:
        - name: ui
          image: cvat/ui:dev
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: cvat-ui
  namespace: platform-evml
  labels:
    app: cvat-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: cvat-ui