apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cvat-redis-inmem-gateway
  namespace: platform-evml
spec:
  servers:
    - port:
        number: 6379
        name: tcp-redis
        protocol: TCP
      hosts:
        - cvat-redis-inmem.cmh.platform-test2.evinternal.net
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cvat-redis-inmem-virtual-service
  namespace: platform-evml
spec:
  gateways:
    - cvat-redis-inmem-gateway
  hosts:
    - cvat-redis-inmem.cmh.platform-test2.evinternal.net
  tcp:
    - match:
        - port: 6379
      route:
        - destination:
            host: cvat-redis-inmem
            port:
              number: 6379
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cvat-redis-inmem-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/data/cvat-redis-inmem'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvat-redis-inmem-pvc
  namespace: platform-evml
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvat-redis-inmem
  namespace: platform-evml
  labels:
    app: cvat-redis-inmem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvat-redis-inmem
  template:
    metadata:
      labels:
        app: cvat-redis-inmem
    spec:
      containers:
        - name: redis
          image: redis:7.2.3-alpine
          ports:
            - containerPort: 6379
              name: redis
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          command:
            - redis-server
            - "--save"
            - "60"
            - "100"
            - "--appendonly"
            - "yes"
          volumeMounts:
            - name: cvat-redis-inmem-storage
              mountPath: /data
      volumes:
        - name: cvat-redis-inmem-storage
          persistentVolumeClaim:
            claimName: cvat-redis-inmem-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cvat-redis-inmem-virtual-service
  namespace: platform-evml
  labels:
    app: cvat-redis-inmem
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
  selector:
    app: cvat-redis-inmem